spring:
    application:
        name: oauth
    datasource:
        driverClassName: org.postgresql.Driver
        password: root123
        url: jdbc:postgresql://localhost:5432/oauthdb
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
          hibernate:
              format_sql: true
